$kind: http-request
name: Update Task
method: PATCH
url: '{{baseUrl}}/api/tasks/{taskId}'
headers:
  - key: Content-Type
    value: application/json
  - key: Authorization
    value: 'Bearer {{token}}'
body:
  type: json
  content: |-
    {
      "title": "Example Title",
      "description": "Example description",
      "statusId": 1,
      "assignedUserId": 1,
      "orderIndex": 0,
      "priority": "Low",
      "dueDate": "2024-01-01T00:00:00Z"
    }
